#ifndef ARGUS_HPP
#define ARGUS_HPP
#include <argus/nanoflann.hpp>
#include <argus/wrinkle_reconstruction/wrinkle_helpers.hpp>
#include <argus/wrinkle_reconstruction/phase_reconstruction.hpp>
#include <argus/get_forces.hpp>
#include <argus/obstacle_helpers.hpp>
#include <argus/scene_animator.hpp>
#include <argus/self_collisions.hpp>
#include <argus/self_collisions_helper.hpp>
#include <argus/wrinkles_solver.hpp>
#include <argus/shared_data.hpp>
#include <argus/obstacles.hpp>
#include <argus/sheet_state_io.hpp>
#include <argus/tfw_gravity.hpp>
#include <argus/geometry_functions.hpp>
#include <argus/symplectic_euler.hpp>
#include <argus/symplectic_euler_wrinkles.hpp>
#include <argus/symplectic_euler_static_wrinkles.hpp>
#include <argus/constraints.hpp>
#include <argus/material.hpp>
#include <argus/sheet.hpp>
#include <argus/util.hpp>
#include <argus/world.hpp>
#include <argus/dynamics_object.hpp>
#include <argus/time_integrator.hpp>
#include <argus/sheet_forces.hpp>
#include <argus/gravity.hpp>
#include <argus/tfw_stretching.hpp>
#include <argus/dphi_penalty.hpp>
#include <argus/tfw_bending.hpp>
#include <argus/thin_shell_bending.hpp>
#include <argus/thin_shell_stretching.hpp>
#include <argus/lbfgs_wrapper.hpp>
#include <argus/lbfgsb_wrapper.hpp>
#include <argus/static_solver.hpp>
#include <argus/graph_coloring.hpp>
#include <argus/optimizers.hpp>
#include <argus/wrinkles_vbd.hpp>
#include <argus/vbd.hpp>
#endif /* ARGUS_HPP */
